version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "my-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-130b20pvk9ovs"
s3_prefix = "my-service"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

