AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spark API - my.service::my-service
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  MyServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: my.service.App::handleRequest
      Runtime: java8
      CodeUri: target/my-service-1.0-SNAPSHOT-lambda-package.zip
      MemorySize: 512
#      Policies: AWSLambdaBasicExecutionRole
      Policies:
        # Give S3 Full Access to your Lambda Function
#        - AmazonS3FullAccess
        - AmazonDynamoDBFullAccess
      Timeout: 40
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  MyServiceApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: MyServiceApi
